# Generated by Django 4.1.2 on 2022-10-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_group', '0004_alter_bloodgroup_table'),
        ('gender', '0004_alter_gender_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('is_deleted', models.BooleanField(default=0)),
                ('blood_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_group.bloodgroup')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender')),
            ],
            options={
                'db_table': 'ums_employee',
            },
        ),
    ]
