# Generated by Django 4.1.2 on 2022-10-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='blood_group_id',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='gender_id',
            new_name='gender',
        ),
    ]
