# Generated by Django 4.1.2 on 2022-10-15 08:24

from django.db import migrations, models
import ums.validators.validate


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeemobile_employeeemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemobile',
            name='mobile_number',
            field=models.CharField(max_length=20, validators=[ums.validators.validate.validate_mobile_number]),
        ),
    ]
