# Generated by Django 4.1.2 on 2022-10-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeemobile_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemobile',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='employeeemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeemobile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='employee.employee'),
        ),
    ]
