# Generated by Django 4.1.2 on 2022-10-12 10:22

from django.db import migrations
from ums.apps.gender.models import Gender

def insertGender(apps, schemaEditor):
    gender = Gender()
    gender.value = 'Male'
    gender.save()
    
    gender = Gender()
    gender.value = 'Female'
    gender.save()
    
    gender = Gender()
    gender.value = 'Not to say'
    gender.status = 0
    gender.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertGender)
    ]
