# Generated by Django 4.1.2 on 2022-10-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0002_auto_20221012_1022'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='umsgender',
        ),
    ]
