# Generated by Django 4.1.2 on 2022-10-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0003_alter_gender_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='ums_gender',
        ),
    ]
