# Generated by Django 4.1.2 on 2022-10-12 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0004_alter_gender_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
