export { UserComponent } from './user.component';
export { ViewUsersComponent } from './component/view-users/view-users.component';
export { SharedModule } from '../../index';
export { UserDetailComponent } from './component/user-detail/user-detail.component';
export { UserFormComponent } from './component/user-form/user-form.component';
export { NewUserComponent } from './component/new-user/new-user.component';
export { EditUserComponent } from './component/edit-user/edit-user.component';
export { PersonalDetailComponent } from './component/personal-detail/personal-detail.component';
export { EducationalDetailComponent } from './component/educational-detail/educational-detail.component';
export { UserResolver } from './service/user.resolver';
export { UserService } from './service/user.service';
export { User } from './model/user';
export { UserFormErrors } from './model/user-form-error';
export { EducationDetail } from './model/education-detail';
export { UserRoutingModule, routingComponents } from './user-routing.module';
