# Generated by Django 4.1.2 on 2022-10-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': "{'database': {'prefix': 'ums'}}blood_group",
            },
        ),
    ]
