# Generated by Django 4.1.2 on 2022-10-12 10:22

from django.db import migrations
from ums.apps.blood_group.models import BloodGroup

def insertBloodGroup(apps, schemaEditor):
    bloodGroup = BloodGroup()
    bloodGroup.value = 'A+'
    bloodGroup.save()
    
    bloodGroup = BloodGroup()
    bloodGroup.value = 'B+'
    bloodGroup.save()
    
    bloodGroup = BloodGroup()
    bloodGroup.value = 'A-'
    bloodGroup.status = 0
    bloodGroup.save()
    
    bloodGroup = BloodGroup()
    bloodGroup.value = 'B-'
    bloodGroup.save()
    
    bloodGroup = BloodGroup()
    bloodGroup.value = 'AB+'
    bloodGroup.save()
    
    bloodGroup = BloodGroup()
    bloodGroup.value = 'O-'
    bloodGroup.status = 0
    bloodGroup.save()
    
    bloodGroup = BloodGroup()
    bloodGroup.value = 'A+'
    bloodGroup.save()
    
    bloodGroup = BloodGroup()
    bloodGroup.value = 'O+'
    bloodGroup.save()
    
    bloodGroup = BloodGroup()
    bloodGroup.value = 'AB-'
    bloodGroup.status = 0
    bloodGroup.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blood_group', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertBloodGroup)
    ]
